name: Build Android ARM64
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: Library
          key: Library-Android-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-Android-


      - name: Build with Unity 2019.4 (IL2CPP, ARM64)
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          unityVersion: 2019.4.40f1
          targetPlatform: Android
          buildMethod: CIBuild.BuildAndroid
          customParameters: -accept-apiupdate
          allowDirtyBuild: true
          androidKeystoreName: svz2.keystore
          androidKeystoreBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          androidKeystorePass: ${{ secrets.ANDROID_KEYSTORE_PASS }}
          androidKeyaliasName: svz2
          androidKeyaliasPass: ${{ secrets.ANDROID_KEYALIAS_PASS }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SvZ2-ARM64
          path: Build/*.apk
          if-no-files-found: error
